import fs from 'fs';
import path from 'path';

const wasmPath = path.resolve('../sandbox/pkg/loki_sandbox_bg.wasm');
const outDir = path.resolve('./src');
const outPath = path.resolve(outDir, 'loki_sandbox_wasm.ts');

if (!fs.existsSync(wasmPath)) {
  console.error("loki_sandbox_bg.wasm not found! Run wasm-pack first.");
  process.exit(1);
}

if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

const wasmBuffer = fs.readFileSync(wasmPath);
const wasmBase64 = wasmBuffer.toString('base64');

const tsContent = `// Auto-generated by inline-wasm.js. Do not edit manually.
export const wasmBase64 = "${wasmBase64}";
`;

fs.writeFileSync(outPath, tsContent);
console.log("Successfully inlined WASM to src/loki_sandbox_wasm.ts");
